name: Pushing Docker image into ECR Action
description: Enhanced composite action for Pushing Docker image into ECR stage
inputs: {}
runs:
  using: composite
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  - name: Push Docker image
    run: docker push ${REPOSITORY_URI}:mavenwebapp-${COMMIT}"
    shell: bash
