name: CI
'on':
  workflow_dispatch: 
  push:
    branches:
    - master
    - main
  pull_request: {}
env:
  IMAGE_TAG: ${BUILD_NUMBER}
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkout
      uses: ./.github/actions/checkout
  build-docker:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - uses: actions/checkout@v4
    - name: Run Build Docker
      uses: ./.github/actions/build_docker
  push-the-artifacts:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - uses: actions/checkout@v4
    - name: Run Push the artifacts
      uses: ./.github/actions/push_the_artifacts
  checkout-k8s-manifest-scm:
    runs-on: ubuntu-latest
    needs: push-the-artifacts
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkout K8S manifest SCM
      uses: ./.github/actions/checkout_k8s_manifest_scm
  update-k8s-manifest-push-to-repo:
    runs-on: ubuntu-latest
    needs: checkout-k8s-manifest-scm
    steps:
    - uses: actions/checkout@v4
    - name: Run Update K8S manifest & push to Repo
      uses: ./.github/actions/update_k8s_manifest___push_to_repo
